### ISSUE TITLE
Replace fallback image with a gender neutral image in Alumni Database cards.

### ISSUE THREAD

**Issue by SudhansuuRanjan** [Rishabh-25-code/alumini-cell-nitp#152]
Replace fallback image with a gender neutral image , Currently it is male.

![image](https://github.com/user-attachments/assets/44d9ee79-da8b-4a4e-8d14-3c96bb80caad)

**Comment by ketansahugit** [comment]
Hi, just wanted you to know that I'm working on this.

**Comment by ketansahugit** [comment]
@SudhansuuRanjan  Could you provide me credentials for the .env file? I wanted to see whether my changes are applying or not.
