### ISSUE TITLE
Add Responsiveness to overview section in alumni corner.

### ISSUE THREAD

**Issue by Rishabh-25-code** [Rishabh-25-code/alumini-cell-nitp#37]
![Isssue 1](https://github.com/Rishabh-25-code/alumini-cell-nitp/assets/72189098/7f982e34-abf9-4a2e-a8e7-59a1b25b6a1e)

1. Make the overview section responsive, replace cards used in **awards**  and **testimonials** if needed.
2. Change images displayed in the carousel.
3. Header section should not be changed.

**Comment by suraj-markup** [comment]
can you assign this to me

**Comment by shivaprasadnashte** [comment]
I want to work on this issue

**Comment by ritikjee** [comment]
I want to work on this issue
