### ISSUE TITLE
Fix styling in Donation page

### ISSUE THREAD

**Issue by SudhansuuRanjan** [Rishabh-25-code/alumini-cell-nitp#45]
![Screenshot (1462)](https://github.com/Rishabh-25-code/alumini-cell-nitp/assets/77230416/74baf996-6dad-413d-9f07-363a2ae3988c)

1. Fix paragraph Styling
2. Fix Button styling
3. Fix input box styling

**Comment by shivaprasadnashte** [comment]
I want to work on this project
