### ISSUE TITLE
Add Form Handling in Registration Page

### ISSUE THREAD

**Issue by SudhansuuRanjan** [Rishabh-25-code/alumini-cell-nitp#46]
![Screenshot (1463)](https://github.com/Rishabh-25-code/alumini-cell-nitp/assets/77230416/87d11d35-5c74-46e6-9785-32a3fa32436b)

1.  Add Form Handling in Registration Page
2.  Add form validation with appropriate error messages.

**Comment by ritikjee** [comment]
I want to resolve this issue.
