### ISSUE TITLE
Add form handling in Donation Page.

### ISSUE THREAD

**Issue by SudhansuuRanjan** [Rishabh-25-code/alumini-cell-nitp#47]
![Screenshot (1462)](https://github.com/Rishabh-25-code/alumini-cell-nitp/assets/77230416/860589ac-e49c-4cb2-a7ce-b371fa8c652f)

1. Add form handling in Donation Page.
2. Add form validation

**Comment by shivaprasadnashte** [comment]
i want to fix this issue
